[phases.setup]
nixPkgs = ['python310', 'nodejs_20']

[phases.install]
cmds = [
  'npm ci --include=dev',
  'pip install -r requirements.txt'
]

[phases.build]
cmds = ['npm run build']

[start]
cmd = 'python server.py'

